select CDCLINOME, LCATDATAHORA from LCATENDIMENTO
    inner join CDCLIENTE on CDCLIENTE.CDCLICODIGO = LCATENDIMENTO.LCACCLIENTE
where (YEAR(LCATDATAHORA) = 2011 and MONTH(LCATDATAHORA) between 1 and 2)
    or (YEAR(LCATDATAHORA) = 2011 and MONTH(LCATDATAHORA) between 7 and 12)
