select CDCLIENTE.CDCLINOME as nome_cliente, count(LCATENDIMENTO.LCACODIGO) as quantidade_atendimentos
from CDCLIENTE
    left join LCATENDIMENTO on CDCLIENTE.CDCLICODIGO = LCATENDIMENTO.LCACLIENTE
group by CDCLIENTE.CDCLINOME;

